name:                SchemeHaskell
version:             0.1.0.0
github:              "RyanAlameddine/SchemeHaskell"
license:             BSD3
author:              "Ryan Alameddine"
maintainer:          "rhalameddine@gmail.com"
copyright:           "2021 Ryan Alameddine"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/RyanAlameddine/SchemeHaskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  SchemeHaskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SchemeHaskell

tests:
  SchemeHaskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SchemeHaskell
